name: ROS2 CI

on: [pull_request, push]

jobs:
  test_environment:
    runs-on: ubuntu-20.04
    steps:
    - uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: galactic
    - uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: ""
        target-ros2-distro: galactic

